version: "3.8"

services:
  wechat:
    build: .
    image: erdong/wechat:latest
    container_name: wechat
    networks:
      wechat:
        ipv4_address: 10.10.0.10
    environment:
      TZ : 'Asia/Shanghai'
    restart: always

networks:
  wechat:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wechat
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"
    name: wechat